# Generated by Django 2.0.3 on 2018-04-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.ManyToManyField(to='attendance.Attendance'),
        ),
        migrations.AddField(
            model_name='user',
            name='reports',
            field=models.ManyToManyField(to='report.Report'),
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(to='core.Student'),
        ),
    ]
