# Generated by Django 2.0.3 on 2018-04-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180401_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
