# Generated by Django 2.0.3 on 2018-04-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
    ]
