# Generated by Django 2.0.3 on 2018-04-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='send_email_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='send_phone_reports',
            field=models.BooleanField(default=True),
        ),
    ]
