# Generated by Django 2.0.3 on 2018-04-01 04:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('organizationmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.OrganizationModel')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('allDay', models.BooleanField(default=False)),
                ('start', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('end', models.DateTimeField(default=None, null=True)),
                ('color', models.CharField(default='#dd356e', max_length=10)),
                ('textColor', models.CharField(default='white', max_length=10)),
            ],
            bases=('core.organizationmodel',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.Event')),
            ],
            bases=('report.event',),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.Report')),
                ('behavior', models.IntegerField(choices=[(0, 'Excellent'), (1, 'Cooperative'), (2, 'Uncooperative')], default=0)),
                ('feeling', models.IntegerField(choices=[(0, 'Energetic'), (1, 'Happy'), (2, 'Active'), (3, 'Sad')], default=0)),
                ('eat_amount', models.IntegerField(choices=[(0, 'All'), (1, 'Half'), (2, 'Little'), (3, 'None')], default=0)),
                ('message', models.TextField(blank=True, max_length=300)),
                ('homework', models.TextField(blank=True, max_length=300)),
            ],
            bases=('report.report',),
        ),
    ]
