# Generated by Django 2.0.3 on 2018-04-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='events',
            field=models.ManyToManyField(related_name='report_events', to='report.Event'),
        ),
    ]
